"""
Visualize Synthetic Training Data for Mandarin Tone Classifier
Shows sample Chao pitch curves generated by train_hybrid_native_model.py
"""

import sys
import os
import numpy as np
import random

# Add scripts dir to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'scripts'))

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

np.random.seed(42)
random.seed(42)

# Import the generate function from the training script
from train_hybrid_native_model import generate_tone_curve

# Generate samples
print("=" * 70)
print("📊 ตัวอย่างข้อมูลสังเคราะห์ที่ใช้เทรนโมเดล")
print("=" * 70)

tone_names = {
    1: "เสียง 1 (High Level 55)",
    2: "เสียง 2 (Rising 35)",
    3: "เสียง 3 (Dipping 214)",
    4: "เสียง 4 (Falling 51)"
}

for tone in [1, 2, 3, 4]:
    print(f"\n{'─' * 70}")
    print(f"🔊 {tone_names[tone]}")
    print(f"{'─' * 70}")
    
    for sample_idx in range(3):
        chao_curve, volume_curve = generate_tone_curve(tone, 50)
        
        # Show 10 sampled points (like the web app does)
        indices = [0, 5, 11, 16, 22, 27, 33, 38, 44, 49]
        sampled = [f"{chao_curve[i]:.2f}" for i in indices]
        
        # Show statistics
        print(f"\n  ตัวอย่างที่ {sample_idx + 1}:")
        print(f"    Chao (10 จุด): [{', '.join(sampled)}]")
        print(f"    Min={chao_curve.min():.2f}  Max={chao_curve.max():.2f}  Mean={chao_curve.mean():.2f}")
        print(f"    Volume range: {volume_curve.min():.2f} - {volume_curve.max():.2f}")
        
        # ASCII mini-graph (height = 5 levels)
        graph_width = 50
        graph_height = 5
        graph = [[' '] * graph_width for _ in range(graph_height)]
        
        for i in range(graph_width):
            level = int(round(chao_curve[i])) - 1  # 0-4
            level = max(0, min(4, level))
            row = 4 - level  # invert (5=top, 1=bottom)
            graph[row][i] = '█'
        
        print(f"    Chao Level:")
        for row_idx, row in enumerate(graph):
            level_label = 5 - row_idx
            print(f"      {level_label} │{''.join(row)}│")
        print(f"        └{'─' * graph_width}┘")
        print(f"        0%                                      100%")

# Show total dataset composition
print(f"\n{'=' * 70}")
print(f"📦 สรุปชุดข้อมูลทั้งหมด")
print(f"{'=' * 70}")
print(f"  จำนวนตัวอย่างทั้งหมด: 80,000")
print(f"  เสียง 1: 20,000 ตัวอย่าง (25%)")
print(f"  เสียง 2: 20,000 ตัวอย่าง (25%)")
print(f"  เสียง 3: 20,000 ตัวอย่าง (25%) — รวม Half-3rd ~35%")
print(f"  เสียง 4: 20,000 ตัวอย่าง (25%)")
print(f"  Train/Val split: 85% / 15%")
print(f"  Input shape: [batch, 2, 50] — 2 channels (Chao + Volume) × 50 time steps")
print(f"\n  Augmentations ที่ใช้:")
print(f"    • Non-linear time warping (±15% sinusoidal)")
print(f"    • Pitch range scaling (85%-115%)")
print(f"    • Global level shift (±0.35)")
print(f"    • Micro-jitter (σ=0.02-0.06)")
print(f"    • Volume envelope (attack/decay)")
print(f"    • Half-3rd tone variation (35% ของเสียง 3)")

# Compare with canonical (ideal) curves
print(f"\n{'=' * 70}")
print(f"📐 เปรียบเทียบ: เส้นมาตรฐาน vs ข้อมูลสังเคราะห์")
print(f"{'=' * 70}")

canonical = {
    1: [5.0, 5.0, 5.0, 5.0, 5.0],
    2: [3.0, 3.4, 3.9, 4.4, 5.0],
    3: [2.2, 1.3, 1.0, 2.3, 4.0],
    4: [5.0, 4.2, 3.1, 1.9, 1.0]
}

for tone in [1, 2, 3, 4]:
    canon = canonical[tone]
    print(f"\n  {tone_names[tone]}:")
    print(f"    เส้นมาตรฐาน (canonical): {canon}")
    
    # Generate 5 samples and show their 5-point versions
    for s in range(5):
        curve, _ = generate_tone_curve(tone, 50)
        pts = [curve[0], curve[12], curve[24], curve[37], curve[49]]
        pts_str = [f"{p:.1f}" for p in pts]
        print(f"    ข้อมูลสังเคราะห์ #{s+1}:       [{', '.join(pts_str)}]")
